[project]
name = "time-machine-bot"
version = "0.1.0"
description = "A Silverback bot for analyzing hypothetical trading scenarios"
dependencies = [
    "silverback>=0.2.0",
    "pandas>=2.0.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"